### ISSUE TITLE
로그인 버튼 클릭 시 아이디 비밀번호를 작성해야 하는 창이 Unable to log in to [product name]이라고 나옵니다.

### ISSUE THREAD

**Issue by lets-gojae** [react-native-seoul/react-native-naver-login#100]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "2.1.1",

### Version of react-native

"react-native": "0.66.1",

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

로그인 버튼 클릭 시 아이디 비밀번호를 작성해야 하는 창이 Unable to log in to [product name]이라고 나옵니다.

### Actual behavior

Unable to log in to [product name]

you cannot log in with your NAVER account due to an error in the [product name] service 라고 나옵니다.

### Tested environment (Emulator? Real Device?)

에뮬레이터 s21

**Comment by mym0404** [comment]
라이브러리와 관계없는 Naver developer console 설정 문제로 보여집니다. [link](https://developers.naver.com/forum/posts/18214)
