### ISSUE TITLE
Safari cannot open the page because the address is invalid with google

### ISSUE THREAD

**Issue by lets-gojae** [react-native-seoul/react-native-naver-login#101]
### Version of naver-login libraries

2.1

### Version of react-native

0.66

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Safari cannot open the page

### Actual behavior

구글과 함께 사용하고 있는데 스키마를 설정을 해도 구글로 로그인하면 스키마가 사라지는 현상이 있습니다.

### Tested environment (Emulator? Real Device?)

시뮬레이터

**Comment by mym0404** [comment]
최신 `2.3.1` 버전에서도 이슈가 재현된다면 다시 댓글 남겨주시길 바랍니다.

추가로 Reproduction repository가 있으면 좋겠습니다.
