### ISSUE TITLE
Could not find com.naver.nid:naveridlogin-android-sdk:4.2.6 error 해결방법 공유합니다.

### ISSUE THREAD

**Issue by minsoo-web** [react-native-seoul/react-native-naver-login#104]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "^2.1.3",

### Version of react-native

"react-native": "0.66.2",

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

yarn android 후 정상 빌드

### Actual behavior

![스크린샷 2021-11-28 오후 8 01 35](https://user-images.githubusercontent.com/57122180/143765116-ee1d68db-c8d7-470c-982e-e5c2644858df.png)

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.naver.nid:naveridlogin-android-sdk:4.2.6.
```
이런 로그가 발생하여 애를 먹었습니다. 

### Tested environment (Emulator? Real Device?)

m1 mac mini
실제기기: 삼성 노트 10 

### 해결 방법

![스크린샷 2021-11-28 오후 8 03 56](https://user-images.githubusercontent.com/57122180/143765179-66718f33-a4f7-4479-8a03-cf016983501a.png)

```gradle

buildscript {
  // ...

  repositories {
   // ...
    jcenter() // add this to repositories
  }

}
// ...

allprojects {
  repositories {
    // ...
    jcenter() // add this
  }
  
}
```
`jcenter()` 라는 코드를 android/build.gradle 파일에 추가해주면 됩니다.

**Comment by kimho** [comment]
어제부터 jcenter가 서비스 종료되어 jcenter()를 추가하는걸로 해결되지 않는 것 같습니다.
다른 해결 방법 아시는 분 계신가요?

**Comment by mym0404** [comment]
현재 `2.3.1` 기준 별도의 `jcenter()` repository 추가 구문이 필요해보이지 않습니다.
