### ISSUE TITLE
Could not find method compile() for arguments [com.facebook.react:react-native:+]

### ISSUE THREAD

**Issue by ejkim-dev** [react-native-seoul/react-native-naver-login#108]
"@react-native-seoul/naver-login": "^2.1.3" 을 현재 사용중인데
안드로이드에서 빌드할 때 /node_modules/@react-native-seoul/naver-login/android/build.gradle 에서 
 compile() for arguments [com.facebook.react:react-native:+] 오류가 납니다. 현재는 해당 파일에서
compile을 implementation로 수정하여 사용하고 있는데 다음 업데이트에 반영해주시면 감사하겠습니다 :)

**Comment by kkch196247** [comment]
```zsh
npm install git+https://git@github.com/kkch196247/react-native-naver-login.git
```

**Comment by kkch196247** [comment]
- ./node_modules/@react-native-seoul/naver-login/android/build.gradle

  ```gradle
  // compile 'com.facebook.react:react-native:+'
  implementation 'com.facebook.react:react-native:+'
  ```

  ```zsh
  npx patch-package @react-native-seoul/naver-login
  ```

  ```zsh
  npx patch-package
  ```

  - https://github.com/ds300/patch-package#readme

**Comment by mym0404** [comment]
AGP가 Gradle과 비슷한 versioning을 따라감에 따라 Gradle `7.x` 부터 `compile`은 완전히 deprecated 되어 error로 처리됩니다.
현재 `2.3.1` 버전에선 `implementation` 으로 구현되어 있습니다.
