### ISSUE TITLE
ios 컴파일중 오류가 납니다.

### ISSUE THREAD

**Issue by skean13** [react-native-seoul/react-native-naver-login#11]
안녕하세요. 입문자이며 ios,xcode지식이 없어서 문의를 드립니다.
expo를 이용해 프로젝트를 구성하였고, 네이버 로그인을 붙이는 중이었습니다.
xcode에서 컴파일중 에러가 납니다.

React/RCTBridgeModule.h file not found 
라고 나옵니다. 
버전은 전부 최신으로 사용했습니다.

<img width="1144" alt="2019-01-03 3 42 25" src="https://user-images.githubusercontent.com/6427924/50606601-a9d5e380-0f09-11e9-9dc7-f00df616c6be.png">

**Comment by hyochan** [comment]
expo는 native module을 지원하지 않는데 알고 계시는지요?
