### ISSUE TITLE
안드로이드 12이슈

### ISSUE THREAD

**Issue by ymc-crow** [react-native-seoul/react-native-naver-login#112]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "2.1.3",

### Version of react-native

0.63.2

### Platforms you faced the error (IOS or Android or both?)

안드로이드

### Expected behavior

패키지 리스트에 넣고 빌드시 manifest파일에 android:exported값 필요.

### Actual behavior

안드로이드 12이상부터는 android:exported가 maifest.xml에 들어가야하는데 빌드시 안들어감 .. 리액트네이티브 빌드로 매번 생성되기 때문에 수동변경도 불가 .. 
com.nhn.android.naverlogin.ui.OAuthCustomTabActivity 요 액티비티가 어디서 붙는지도 모르겟습니다. ㅜㅜ

### Tested environment (Emulator? Real Device?)

에뮬레이터로테스트중입니다. 구글픽셀 5, 안드로이드 12

* What went wrong:
Execution failed for task ':app:installProdDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl613678168.tmp/base.apk (at Binary XML file line #451): com.nhn.android.naverlogin.ui.OAuthCustomTabActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

**Comment by khyun-digital-x** [comment]
Android SDK 31 버전에서 해당 커밋이 정상적으로 동작함을 확인했습니다.

해결법을 찾다가 한줄기 빛이 되어주셨네요.

감사합니다.

**Comment by mym0404** [comment]
https://github.com/naver/naveridlogin-sdk-android/releases
네아로 sdk 5.0.0 부터 API 12 대응됩니다.

**Comment by mym0404** [comment]
보니까 네아로 5.0.0 부터 패키지도 달라지고 API도 변경되어 이 repo의 구현이 바뀌어야하는 상황인 것 같습니다.
해결책은 manifest에서 다음과 같이 exported를 replace 치면 됩니다.
```xml
      <activity
            android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
            android:exported="true"
            tools:replace="exported" />
```

**Comment by kkch196247** [comment]
```zsh
npm install git+https://git@github.com/kkch196247/react-native-naver-login.git
```

**Comment by kkch196247** [comment]
- ./android/app/src/main/AndroidManifest.xml

  ```xml
  <manifest
    _="#ADD:"
    xmlns:tools="http://schemas.android.com/tools"
    ______="">
    <application>
      <!-- #ADD: -->
      <activity
        android:name="com.nhn.android.naverlogin.ui.OAuthLoginActivity"
        android:exported="false"
        tools:node="merge" />
      <activity
        android:name="com.nhn.android.naverlogin.ui.OAuthLoginInAppBrowserActivity"
        android:exported="false"
        tools:node="merge" />
      <activity
        android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
        android:exported="false"
        tools:node="merge" />
      <!--  -->
    </application>
  </manifest>
  ```

**Comment by mym0404** [comment]
Closed by bumping android sdk `5.1.0`
