### ISSUE TITLE
네이버 어플 이동 후 전혀 다른 어플로 이동합니다.

### ISSUE THREAD

**Issue by boodong-rn** [react-native-seoul/react-native-naver-login#115]
### Version of naver-login libraries

v2.1.3
### Version of react-native

v0.66.3
### Platforms you faced the error (IOS or Android or both?)

iOS
### Expected behavior

네이버 앱으로 이동 후에 다시 저희 어플로 돌아와야 합니다.

### Actual behavior
네이버 앱으로 이동 후 전혀 다른 어플로 이동합니다.

### Tested environment (Emulator? Real Device?)

iPhone SE2
OS: 15.3.1

**Comment by mym0404** [comment]
#57 에 단 댓글 참고해주세요.
