### ISSUE TITLE
TypeError: Cannot read property 'login' of undefined 에러

### ISSUE THREAD

**Issue by doosanehi** [react-native-seoul/react-native-naver-login#117]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "^2.1.3",

### Version of react-native

    "react-native": "0.68.0",

### Platforms you faced the error (IOS or Android or both?)

both 

### Expected behavior

[NaverLoginExample](https://github.com/react-native-seoul/react-native-naver-login/tree/master/NaverLoginExample) 에 나와있는 예제코드를 그대로 따라해 보았으나 실행이 되지 않습니다..

### Actual behavior

![Screen Shot 2022-04-26 at 19 31 17](https://user-images.githubusercontent.com/89623787/165282192-a5bebb72-dc53-4cfa-ae38-fa6bd791631f.png)

![Screen Shot 2022-04-26 at 19 31 42](https://user-images.githubusercontent.com/89623787/165282424-8cfce1f5-85e8-4811-9560-ee330f2c150f.png)

이렇게 에러가 뜨고 

에러가 난 코드의 경로를 따라가다보면 
`node_modules/@react-native-seoul/naver-login/index.js`

```typescript
import { NativeModules, Platform } from "react-native";
var IosNaverLogin = NativeModules.IosNaverLogin, RNNaverLogin = NativeModules.RNNaverLogin; // 여기 이름은 달라야 함.
var NaverLoginIos = {
    login: function (param, callback) {
        IosNaverLogin.login(param, callback);
    },
    logout: function () {
        IosNaverLogin.logout();
    },
};
var RNNaverLoginAndr = {
    login: function (param, callback) {
        RNNaverLogin.login(param, callback);
    },
    logout: function () {
        RNNaverLogin.logout();
    },
};
export var getProfile = function (token) {
    return fetch("https://openapi.naver.com/v1/nid/me", {
        method: "GET",
        headers: {
            Authorization: "Bearer " + token,
        },
    })
        .then(function (response) { return response.json(); })
        .then(function (responseJson) {
        return responseJson;
    })
        .catch(function (err) {
        console.log("getProfile err");
        console.log(err);
    });
};
export var NaverLogin = Platform.OS === "ios" ? NaverLoginIos : RNNaverLoginAndr;
```

`node_modules/@types/react-native/index.d.ts`

```typescript
/**
 * Interface for NativeModules which allows to augment NativeModules with type informations.
 * See react-native-sensor-manager for example.
 */
interface NativeModulesStatic {
    [name: string]: any;
}

/**
 * Native Modules written in ObjectiveC/Swift/Java exposed via the RCTBridge
 * Define lazy getters for each module. These will return the module if already loaded, or load it if not.
 * See https://reactnative.dev/docs/native-modules-ios
 * @example
 * const MyModule = NativeModules.ModuleName
 */
export const NativeModules: NativeModulesStatic;
```

이런 코드들이 있습니다. 개발을 시작한 지 얼마 되지 않아 질문이 정리가 안되어있는 점 양해 부탁드립니다.

어느부분에서 문제가 있는 것인지 궁금합니다..

### Tested environment (Emulator? Real Device?)

갤럭시 s22 (API30)
아이폰 12 (ios 15.4)

**Comment by mym0404** [comment]
1. 라이브러리 install 시 `pod install` 을 실행시켜 주셨나요?

현재 최신 버전인 `2.3.1` 이슈가 재현된다면 댓글 남겨주세요.
