### ISSUE TITLE
RefreshToken 기능은 없는건가요?

### ISSUE THREAD

**Issue by dev4141** [react-native-seoul/react-native-naver-login#12]
안녕하세요

좋은 react-native 라이브러리를 만들어주셔서 감사합니다.

이 라이브러리를 사용중이긴하는데요.

제가 소스를 잘 파헤치지 못해서 그런지 기능을 알지 못해서 로그인 후 얼마후에 accesstoken 이 만료가 되어 024 에러가 나더라고요

app 을 제실행해도 어느정도까지는 되는데 한5시간 정도 후에는 accesstoken 이 만료되는 거 같아서요.

혹시나 refresh token 을 받을 수 있는 방법이 있을까요?

현재 사용 OS  IOS 입니다.

제가 뭔가 설정을 잘못한걸까요?

도움 좀 부탁드립니다.

**Comment by hyochan** [comment]
네 네이티브르르 전혀 모르시는 분들의 급한 요청이 있어 최소 기능만 빠르게 올렸습니다. 개발하시다가 추가 요구되는 부분이 있으시면 가급적 `PR`을 주시면 신속히 `merge`하고 `npm`에 배포하도록 하겠습니다.

**Comment by JJMoon** [comment]
iOS에서 토큰 만료되면 다시 가져오는 부분이 있습니다. 현재 저희 프로덕션에서 그렇게 잘 작동하고 있습니다.

**Comment by JJMoon** [comment]
@dev4141 
부연 설명 드리자면, 네아로 토큰은 1시간동안 유효하고, 그 후 갱신됩니다. 
갱신할 때 네이버 앱이 설치되어 있으면 네이버 앱으로 이동하여 자동갱신 후 내 앱으로 돌아오고, 웹뷰를 이용할 때에는 다시 아이디/비번을 입력하여야 합니다.
아마 안드로이드도 비슷할 것 같습니다.

**Comment by kofsiwon** [comment]
저도 024 뜸 ㅠㅠ 갑자기 왜이러지 ㅋㅋ 1시간도 아니고 그냥 처음부터 안됨 ㅋㅋ
 Nearo accessToken ::  AAAAOF6ks5Db8Oqzy-vKoa0ieL30DtbgNBnJKch8NKaVFiK9XQyg9B-celz59dfWGzOqmDf7Kb5M9318dNJxIixhz6Y

 Nearo refreshToken :: NnYumT1KLKT7cGwKCPxmgStXhoxUMsisq3C1isEMbScvEn4isq9J1h2Nis5JD0ipx7NHYOtZ5cj1BwVqHKLmByipD2ogANXa2dSIxpM0vSrRryqr8O4DY685isyBbFKLipFtjMSH

 Nearo Token  ::   >>>>>>>>  VALID 바로 RN 로 넘겨줌.

 Nearo Token 비면 안되는거져?
