### ISSUE TITLE
Could not find method compile() for arguments [com.facebook.react:react-native:+]

### ISSUE THREAD

**Issue by web-sejin** [react-native-seoul/react-native-naver-login#127]
"@react-native-seoul/naver-login": "2.2.0" = 해당 라이브러리 버전입니다.
"react-native": "0.68.2" = 리액트 네이티브 버전입니다.

해당 라이브러리를 설치 후 안드로이드 빌드를 하면 
Could not find method compile() for arguments [com.facebook.react:react-native:+] 
해당 오류가 발생합니다.

왜 그러는 걸까요 ㅠ

**Comment by jungseungjin** [comment]
naver-login/android/build.gradle 파일에서 제일 아래 

dependencies {
  implementation 'com.facebook.react:react-native:+'   // <-여기가 compile로 시작할텐데 implementation로 변경해주시면 빌드될겁니다.
  implementation 'com.navercorp.nid:oauth:5.1.0'
}

**Comment by mym0404** [comment]
Gradle 7.x 이상부터 `compile`은 빌드시에 에러가 납니다.

현재 라이브러리 최신 버전에서는 `implementation` 으로 구현되어있습니다.
