### ISSUE TITLE
원래 뒤로가기 버튼은 없는건가요?

### ISSUE THREAD

**Issue by seongminchoob** [react-native-seoul/react-native-naver-login#13]
<img width="336" alt="2019-02-04 6 41 52" src="https://user-images.githubusercontent.com/35505959/52201044-a2f61400-28ad-11e9-883c-38782e47885e.png">

로그인 창으로 가면 이렇게 뒤로가기 버튼이 없는데 원래 이렇게 되도록 설계된건가요? 그러면 그 기능을 넣으려면 어디부분을 건드려야하나요?

**Comment by seongminchoob** [comment]
아 글의 서두가 사라져있네요; 이런기능 npm 만들어주셔서 대단히 감사합니다

**Comment by hyochan** [comment]
@seongminchoob ios에서 왼쪽 상단에 보시면 `go back to app` 같이 뒤로 가는 interface를 제공할텐데 naver sdk안에서 내장 `webview`를 띄워서 저렇게 보이나 보네요. `naver sdk` 내부에서 `webview`를 띄우는 곳에 접근하여 상단에 바를 만들어주시던지 (매번 sdk 업데이트시마다 수작업을 해줘야 하니 추천드리지는 않습니다..) 꼭 필요한 부분이면 고민을 좀 해봐야할 것 같습니다. 안드로이드 같은경우 `default back` 버튼이 존재하고 `ios`같은 경우 왼쪽 swipe로 돌아갈 수 있으니 괜찮을 것 같기도 하고요.

**Comment by seongminchoob** [comment]
넵.. 왼쪽 swipe가 직관적이지는 않아서 이 상태로는 사용하는데에는 불편함이 좀 있을것 같습니다... 아니면 혹시 native module을 어떻게 연결했는지 대충 구조만 설명해주실수 있으신가요? ㅠㅠ 제가 objective C는 제대로 배워본 적이없어서 코드읽는데 너무 힘들더라고요.. ㅠ

**Comment by hyochan** [comment]
@seongminchoob 혹시 android 유저이신지요? 왠만한 `ios`사용자들은 왼쪽 swipe로 뒤로갈 수 있는 것을 인지할 것 같은데요? 그리고 수정을 원하시면 브릿지가 아니라 `naver sdk`를 수정하셔야 할거에요~

말씀하신 내용은 공식 문서를 참고했어요.
https://facebook.github.io/react-native/docs/native-modules-ios

**Comment by seongminchoob** [comment]
조금전에 확인해본 결과 스와이핑해도 창이 닫히지 않는걸 확인했습니다! 그리고 아이폰 유저입니다. 물론 대부분 사용자들이 swipe을 인지할수있더라도 cancel button이 없다는거 자체가 UX에 좀 많이 문제가 될꺼같아서요 ㅎㅎ.. 그리고 창 하단의 하얀색 부분의 오른쪽 하단 부분을 클릭하면 등록해놓은 kServiceAppUrlScheme로 가지는 것도 확인했습니다. 이것도 의도하신건지 궁금합니다!

**Comment by heyman333** [comment]
최신 SDK 에서 다음처럼 나오는 것을 확인했습니다.
![naver-login](https://user-images.githubusercontent.com/22214150/69447677-54f9c080-0d9a-11ea-8abe-6feb7dfb35c7.png)
