### ISSUE TITLE
Execution failed for task ':react-native-seoul-naver-login:generateDebugRFile'.

### ISSUE THREAD

**Issue by ppsea** [react-native-seoul/react-native-naver-login#134]
naver-login libraries `2.2.0`
react-native `0.68.2`
kotlin `1.6.0`
Android / Emulator / google pixel 2

### Expected behavior

에뮬레이터 종료 후 npm run android로 build 성공

### Actual behavior

- 에뮬레이터 종료 후 새롭게 빌드 시 빌드 실패가 반복적으로 발생함.
- yarn remove react-native-seoul/naver-login && yarn add react-native-seoul/naver-login 하여 재설치하면 빌드 됨.

FAILURE: Build failed with an exception.

- What went wrong:
Execution failed for task ':react-native-seoul-naver-login:generateDebugRFile'.

> A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
/Users/henry/Works/pikurate-app/node_modules/@react-native-seoul/naver-login/android/build/intermediates/local_only_symbol_list/debug/R-def.txt
>

**Comment by gun-bro98** [comment]
혹시 문제 해결하셨나요? 저도 똑같은 문제가 있습니다

**Comment by mym0404** [comment]
`2.3.1` 에서 재현이 되시나요? 
Reproduction repository가 있으면 좋을 것 같습니다.
해당 이슈 지속되면 댓글 남겨주세요.
