### ISSUE TITLE
네이버 앱이 설치되어있으면 앱으로 자동이동 여부

### ISSUE THREAD

**Issue by cocoburger** [react-native-seoul/react-native-naver-login#135]
### Version of naver-login libraries

    "@react-native-seoul/naver-login": "^2.1.3",

### Version of react-native

 "0.67.1",

### Platforms you faced the error (IOS or Android or both?)

Android

### Actual behavior

ios는 네이버 앱으로 인증하는 방식과, SafariViewContoller로 인증하는 방식 2가지 방식을 설정할 수 있는데
안드로이드는 따로 설정하는 부분이 없어서요.
안드로이드는 앱이 깔려 있으면 자동으로 앱으로 이동시켜주나요?
### Tested environment (Emulator? Real Device?)

pixel_4_xl (애뮬레이터)

**Comment by mym0404** [comment]
현재 그렇습니다.
