### ISSUE TITLE
android 버전 Usage 참고하여 진행하였으나 동작하지 않습니다. 

### ISSUE THREAD

**Issue by colinder** [react-native-seoul/react-native-naver-login#136]
### Version of naver-login libraries

"version": "2.3.0",

"react-native": "0.67.0"  / Android 

### Expected behavior
button 클릭 후 네이버 로그인 창 팝업 등장.

### Actual behavior
button 클릭 후 nid.naver.com 에 접속은 되나 이후 흰 배경 노출하고 아무런 반응이 없음(error도 없음)
혹은 검정 화면으로 전환 후 아무런 반응이 없음.

### Tested environment (Emulator? Real Device?)
Emulator

### context
문서를 따라 npm 설치 후 
네이버 로그인을 사용할 파일로 이동해 
import { NaverLogin, getProfile } from "@react-native-seoul/naver-login";한 후 
Usage의 코드를 그대로 가져와 사용, 
button에 함수를 달고 클릭하면 화면 전환 후 흰 배경으로 nid.naver.com으로 접속하는 화면이 뜨고 흰 배경이 노출 

이후 아무런 동작이 없음. 
어플 종료 후 재실행하면 button 클릭 시 검정 화면으로 전환되고 이후 아무런 동작이 없습니다. 

naverLogin 함수에 들어가나, NaverLogin.login() 에서 동작하지 않습니다.
에러도 나지 않는데. 혹시 어떤 것이 문제일까요..?

**Comment by mym0404** [comment]
API 사용엔 문제가 없어보이나 네이버 개발자 콘솔에서의 설정과 관련도니 문제같습니다.
[link](https://developers.naver.com/docs/login/devguide/devguide.md#3--%EB%84%A4%EC%9D%B4%EB%B2%84-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%A0%81%EC%9A%A9)

를 읽고 다시 설정해보시는 것을 추천드립니다.
이슈가 지속된다면 새롭게 이슈를 열어주세요.
