### ISSUE TITLE
로그인 창이 오픈되지 않고 관리자에게 문의하라는 페이지가 오픈됩니다

### ISSUE THREAD

**Issue by kimjoshua** [react-native-seoul/react-native-naver-login#137]
### Version of naver-login libraries

    "@react-native-seoul/naver-login": "^2.3.0",

### Version of react-native

    "react-native": "^0.68.2",

### Platforms you faced the error (IOS or Android or both?)
안드로이드 11.0

### Expected behavior

로그인 입력창이 나오지 않고 관리자에게 문의하라는 에러가 출

### Actual behavior

 kConsumerKey: 네이버에서 받은 코드 입력,
  kConsumerSecret: '네이버에서 받은 코드 입력',
  kServiceAppName: '앱이름',
모두 적용
### Tested environment (Emulator? Real Device?)

Pixel XL API 30 11.0

**Comment by HoJin9622** [comment]
안드로이드 앱 패키지 이름이 동일한가요?

**Comment by mym0404** [comment]
콘솔 설정과 관련된 이슈같습니다.
이 라이브러리에서 관리될 이슈가 아닌것 같습니다.
[link](https://developers.naver.com/forum/posts/28131)
