### ISSUE TITLE
could not find a declaration file for module... 에러 관련 질문드립니다.

### ISSUE THREAD

**Issue by jihyeonjeong11** [react-native-seoul/react-native-naver-login#14]
좋은 모듈을 만들어주셔서 감사합니다.
리액트 네이티브를 처음 써보는 터라 link를 했음에도 서드파티 모듈을 불러오지 못하는것 같은데
어떤 점이 문제인지 알고 싶습니다.

**Comment by hyochan** [comment]
안녕하세요. 답변이 늦어져서 죄송합니다. 혹시 어떻게 시도해서 어떤 오류가 나오는지 추가적으로 알 수 있을까요?
