### ISSUE TITLE
Task :react-native-seoul-naver-login:verifyReleaseResources 해결법

### ISSUE THREAD

**Issue by jyy9501** [react-native-seoul/react-native-naver-login#142]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "^2.3.0"

### Version of react-native

"react-native": "0.69.5"

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

android build

### Actual behavior

"Task :react-native-seoul-naver-login:verifyReleaseResources" 발생

### Tested environment (Emulator? Real Device?)

Device

![image](https://user-images.githubusercontent.com/54612074/192232641-b3105d90-54b0-418d-b367-568ea7799193.png)

/node_modules/@react-native-seoul/naver-login/android/build.gradle 파일 다음과 같이 변경후 해결되었음

**Comment by YongHoonJJo** [comment]
감사합니다 :)
