### ISSUE TITLE
button click시 네이버 웹에서의 에러 

### ISSUE THREAD

**Issue by kimk1029** [react-native-seoul/react-native-naver-login#16]
<img width="315" alt="Screen Shot 2019-04-04 at 1 22 37 AM" src="https://user-images.githubusercontent.com/11432479/55495637-52662180-5678-11e9-82ce-f3e47be8291d.png">
나와있는대로 다등록을맞게하였는데
버튼 클릭하자마자 이렇게 뜨네요 사용할수없다던데 무슨이유일까요.

**Comment by kimk1029** [comment]
url 스키마 문제라고들하는데 
![trouble](https://user-images.githubusercontent.com/11432479/55603719-0c5bab80-57a7-11e9-88a2-54d765727ff3.png)
앱등록할때 url 스키마 를 url 말고 콜백펑션이름을 저렇게 주었어요 .
컴퓨터에 xcode로 프로젝트열어서 plist 파일안에도 저렇게 스키마값일치시켜주엇구요...

**Comment by JJMoon** [comment]
URL scheme 은 잘 겹치지 않는, 좀 긴 이름이 좋습니다. 페북같은 경우 고유의 아이디를 주고 있구요..
myappnameandnaverlogin  이런 식이 좋을 것 같습니다.
