### ISSUE TITLE
Naver App으로 실행했을 경우 별도의 처리가 필요한가요?

### ISSUE THREAD

**Issue by dotkebi** [react-native-seoul/react-native-naver-login#17]
* iOS에서 네이버 앱이 설치되어 있지 않은 경우 웹뷰로 로그인 하고 `promise`가 정상적으로 콜백 됩니다.

* 네이버앱이 설치된 경우 앱 로그인 후에 foreground되면서 동작을 따로 안하는 것 같습니다.

구현이 안된 것인지, 따로 추가 작업을 해줘야 하는지 궁금합니다.

**Comment by JJMoon** [comment]
앱 설치된 경우 로그인 후 돌아오는 부분도 잘 작동합니다. 이 부분 세팅은 readme 를 잘 따라하시면 될 것 같습니다. 네이버쪽 문서를 같이 참고하시면 도욱 좋을 듯 합니다.

**Comment by dotkebi** [comment]
@JJMoon 
네 해결했습니다. 감사합니다.
