### ISSUE TITLE
Android 9 앱 꺼짐

### ISSUE THREAD

**Issue by kangjor** [react-native-seoul/react-native-naver-login#20]
버전 8까지는 잘 되는데 9(pie)부터 
로그인화면에서 아이디 패스워드 입력하고 
로그인 버튼 클릭하면 앱이 꺼집니다. 

이런현상 있으신 분 없으신가요??

**Comment by hyochan** [comment]
@kangjor `logcat`에서 확인할 수 있는 디버그 콘솔을 공유해주시면 좋을 것 같습니다!

**Comment by neojake** [comment]
@kangjor 저도 그러길래 네이버 sdk 파일 업데이트 하니 정상작동하였습니다.

**Comment by JJMoon** [comment]
@kangjor 안드로이드 sdk 가 오래전 버전이라.. ㅠㅠ  공유 감사합니다.

**Comment by JJMoon** [comment]
@neojake @hyochan 지난번에 모듈 업데이트 관련해서 작업해둔거 PR 올렸습니다. 두분이 테스트 하시고 보완하신 후 반영 부탁드립니다.

**Comment by neojake** [comment]
@JJMoon 테스트해보니 잘되네요~ 감사합니다^^

**Comment by kangjor** [comment]
@JJMoon @neojake 정상작동합니다. 정말 감사합니다. ^^
