### ISSUE TITLE
[ios] 해당 라이브러리를 사용 중 웹뷰 로그인으로밖에 로그인되지 않습니다

### ISSUE THREAD

**Issue by jihyeonjeong11** [react-native-seoul/react-native-naver-login#24]
좋은 라이브러리를 만들어 주셔서 감사합니다.

네이버 디벨로퍼 및 해당 readme를 활용해 로그인은 실제로 잘 됩니다만,

기기에서 네이버 앱이 깔려 있을 경우 이를 인지하지 못하고 웹뷰 로그인만 가능한 문제가 있습니다.

네이티브 개발에 대한 경험이 없는 관계로 이렇게 질문을 드립니다.

혹시 어떤 부분을 제가 다시 확인해야 앱 연동이 가능한지 알려주시면 감사하겠습니다.

**Comment by JJMoon** [comment]
현재 버전으로, iOS에서 네이버 앱으로 이동하여 잘 됩니다. Readme와 함께 네이버 문서도 리뷰하시면 좋을 것 같습니다. 혹시 문서에 빠진게 있으면 알려주시거나 풀 리퀘스트도 환영합니다.
감사합니다.
