### ISSUE TITLE
0.60 버전에서 링크시 React/RCTDefines.h 를 찾을수 없음

### ISSUE THREAD

**Issue by wemeet-developer-admin** [react-native-seoul/react-native-naver-login#26]
안녕하세요 0.60버전에서 설치시

오토링크를 통해 pod으로 설치하면 login 메소드를 찾을수 없다고 나옵니다.
그래서 매뉴얼 링크를 하면 React/RCTDefines.h를 찾을 수 없다고 나옵니다.

혹시 해결방법이 있을까요??

**Comment by JJMoon** [comment]
iOS 는 기존 매뉴얼 링크로 하시기 바랍니다. iOS sdk 버전업 할 때 이 부분도 같이 검토할 예정입니다.
피드백 감사합니다.

**Comment by warmherz** [comment]
답변이 조금 이상한데요. 매뉴얼 링크로 했지만 'React/RCTDefines.h를 찾을 수 없다'고 나오는데요. 이에 대한 해결책은 무엇인가요?

**Comment by tvl-jyoon** [comment]
저도 매뉴얼 링크를 해도 React/RCTDefines.h 를 찾을 수 없다고 나오네요

In file included from /Users/jungyeon.yoon/Dev/hummingbird-alpha/AppService/node_modules/react-native-naver-login/ios/IosNaverLogin.h:3:
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by mk0116** [comment]
libraries에서 naver login을 제거
react-native link react-native-naver-login
cd ios && pod install

이러면 위 빌드 에러는 해결이 됩니다.(rn 0.60부터 변경사항)

**Comment by mk0116** [comment]
pod로 integration하고나면 이번엔
NaverThirdPartyLoginConnection.h 파일을 찾을수 없다고 나오네요.
라이브러리에서 pod와 제대로된 integration을 지원할 필요가 있어 보입니다.

**Comment by JJMoon** [comment]
답변이 늦었습니다. 조만간 iOS SDK 버전도 최신으로 올리고, 이 부분 디버깅도 하겠습니다.
