### ISSUE TITLE
[How to..] 404 page is not found after priavate info confirm. 

### ISSUE THREAD

**Issue by saeromCho** [react-native-seoul/react-native-naver-login#52]
### Version of kakao-login libraries
@2.1.0

### Version of react-native
@0.61.5

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
로그인 시, 개인정보활용 동의를 한 후에, 정상 로그인이 되어서 redirect URL로 설정해준 url로 이동을 해야 합니다.

### Actual behavior
![스크린샷 2020-02-26 오후 3 56 41](https://user-images.githubusercontent.com/28703206/75321028-4946fa00-58b3-11ea-902e-09a7b0302efa.png)
아이디와 패스워드를 입력하고, 개인정보활용을 동의 버튼을 누르면 나오는 화면입니다.
어떠한 점이 문제인지 말씀주시면 감사드리겠습니다.
답변 기다리겠습니다. 감사합니다.

### Tested environment (Emulator? Real Device?)
Emulator입니다.

**Comment by heyman333** [comment]
@saeromCho 입력하신 소스를 좀 올려주실 수 있을까요?

**Comment by sonson1023** [comment]
저도 같은 문제를 가지고 있습니다만 해결 방법을 못찾겠네요 ㅠㅜ

**Comment by sonson1023** [comment]
> 저도 같은 문제를 가지고 있습니다만 해결 방법을 못찾겠네요 ㅠㅜ

저의 경우 URL Scheme 에 _ 가 있어서 문제가 발생했습니다.

**Comment by mym0404** [comment]
최신 라이브러리 버전 `2.3.1` 에도 동일한 현상이 일어난다면 새롭게 이슈를 열어주시면 감사하겠습니다.
참고로 본 라이브러리는 모바일 앱만 지원을 하고있어 설정 과정에서 따로 Redirect url이 필요하지 않습니다.
