### ISSUE TITLE
네이버 앱이 없을 때 반응이 없습니다.

### ISSUE THREAD

**Issue by warmherz** [react-native-seoul/react-native-naver-login#55]
### Version of kakao-login libraries
2.1.0

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
iOS only

### Expected behavior
네이버 앱이 설치되어 있지 않을 땐 WebView 로 네이버 로그인창이 떠야함.

### Actual behavior
네이버 앱이 없는 상태에서 네이버 로그인 버튼을 누르면 아무 반응이 없습니다.
ios debug 창에서는 아래와 같은 메시지만 뜹니다.
-canOpenURL: failed for URL: "naversearchapp://" - error: "작업을 완료할 수 없습니다.(OSStatus 오류 -10814.)"
-canOpenURL: failed for URL: "naversearchthirdlogin://" - error: "작업을 완료할 수 없습니다.(OSStatus 오류 -10814.)"

### Tested environment (Emulator? Real Device?)
Real device - iPhone7 에서 확인하였습니다.

**Comment by heyman333** [comment]
#58 참고해보실래요?

**Comment by mym0404** [comment]
현재 최신 버전인 `2.3.1` 버전으로 시도해보시고 문제가 있으시면 다시 댓글 남겨주세요.
