### ISSUE TITLE
네이버 앱이 설치 되어 있지 않을때 응답이 없습니다.

### ISSUE THREAD

**Issue by KimChungHun** [react-native-seoul/react-native-naver-login#58]
### Version of kakao-login libraries

2.1.0

### Version of react-native

0.61.5

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

네이버 앱이 설치 되어 있지 않아 WebView로 로그인 창이 노출됨,
로그인 후 WebView 페이지에서 노출된 동의 버튼을 선택 하였으나 이후 token을 받지 못하고 error를 받고 있음

### Actual behavior

WebView 페이지에서 노출된 동의 버튼을 선택 하였으나 이후 token을 받지 못하고 error를 받고 있음
token은 null을 받고 error를 리턴 받고 있음(errCode: user_cancel, errDesc: user_cancel). 

### Tested environment (Emulator? Real Device?)

LG V30, LG V40

**Comment by KimChungHun** [comment]
https://www.mrlatte.net/code/2019/11/08/naver-login-user-cancel.html
해당 사이트에서 확인 후 해결함

**Comment by heyman333** [comment]
@KimChungHun 감사합니다 다음 업데이트때 해당 내용 포함해서 배포 하겠습니다.
