### ISSUE TITLE
logout함수 리턴값 스펙

### ISSUE THREAD

**Issue by mnkang89** [react-native-seoul/react-native-naver-login#63]
### Version of naver-login libraries
2.1.0

### Version of react-native
0.61

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
NaverLogin.logout함수 호출시 promise 반환

### Actual behavior
NaverLogin.logout함수 호출시 반환값 없음.

-> 로그아웃 실패케이스가 절대 발생하지 않는것이 보장되는것이 아니라면 카카오 로그아웃처럼 promise형태로 에러핸들링이 가능하거나 실제 return value자체가 '로그아웃 성공여부'에 대한 구분값을 명시적으로 리턴해주면 좋지 않을까 합니다! 혹시 절대 실패하지 않나요?ㅎㅎ..

### Tested environment (Emulator? Real Device?)
Emulator, Real Device 

고생해주셔서 정말 잘쓰고 있고 매번 정말 감사드립니다.

**Comment by mym0404** [comment]
`3.x` 에서 관련 API 들을 `Promise`로 처리할 것이고 개선할 예정입니다.
