### ISSUE TITLE
XCode 12 업댓 후 iOS 시뮬에서 빌드가 안됩니다.

### ISSUE THREAD

**Issue by kofsiwon** [react-native-seoul/react-native-naver-login#66]
### Version of naver-login libraries
@react-native-seoul/naver-login": "^2.1.0

### Version of react-native
react-native-cli: 2.0.1
react-native: 0.60.6

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
빌드 성공

### Actual behavior
금요일까지 잘되었었는데 업댓하고나서 시뮬에서 빌드가 안됩니다. XCode 12로 업글해서 그런가
2.0.0 였는데 혹시나해서 업댓해봤지만 소용 없음

ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/leesam/Desktop/Projects/React/src/memorypen/ios/Pods/naveridlogin-sdk-ios/NaverThirdPartyLogin.framework/NaverThirdPartyLogin' for architecture arm64

### Tested environment (Emulator? Real Device?)
XCode 12
iPhone X, iPhone 11 Pro Simulator로 해봄

**Comment by wkddnjset** [comment]
![image](https://user-images.githubusercontent.com/22087542/95358476-11ea0280-0904-11eb-9715-01a36b81a2c0.png)

`Project` > `Info 탭` > `Architectures` > `Excluded Architectures` 에 arm64 추가하니깐 됬습니다!

**Comment by kofsiwon** [comment]
> @kofsiwon
> 
> ![image](https://user-images.githubusercontent.com/22087542/95358476-11ea0280-0904-11eb-9715-01a36b81a2c0.png)
> 
> `Project` > `Info 탭` > `Architectures` > `Excluded Architectures` 에 arm64 추가하니깐 됬습니다!

감사합니다. 저도 한번 해봐야 겠네요
