### ISSUE TITLE
[ios] Reason: image not found

### ISSUE THREAD

**Issue by wkddnjset** [react-native-seoul/react-native-naver-login#67]
### Version of naver-login libraries
2.1.0

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
IOS

### Actual behavior

빌드가 정상적으로 되지 않습니다.
```
dyld: Library not loaded: @rpath/NaverThirdPartyLogin.framework/NaverThirdPartyLogin
  Referenced from: /Users/seojang-won/Library/Developer/CoreSimulator/Devices/.../Project.app/Project
  Reason: image not found
```

### Tested environment (Emulator? Real Device?)

현재 Xcode 12, ios 14 버전, iPhone 11 Emulator로 로컬 테스트 시 발생하는 문제입니다.

### 추가

naver-ios-sdk에서 [[동일이슈](https://github.com/naver/naveridlogin-sdk-ios/issues/4)]가 있었으며, 똑같이 해봤는데 안됩니다.

**Comment by mym0404** [comment]
현재 최신 버전인 `2.3.1` 버전으로 시도해보시고 문제가 있으시면 다시 댓글 남겨주세요.
