### ISSUE TITLE
xcode 빌드 시 오류가 발생합니다.

### ISSUE THREAD

**Issue by ssif** [react-native-seoul/react-native-naver-login#68]
### Version of naver-login libraries
2.1.0

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
IOS SDK : 14.1
xcode : 12.1

### Expected behavior
정상 빌드 완료

### Actual behavior
xcode 빌드 시 오류가 발생합니다.

Showing All Errors Only

Building for iOS Simulator, but linking in dylib built for iOS, file /Users/UserAccount/Downloads/MyNewApp/ios/Pods/naveridlogin-sdk-ios/NaverThirdPartyLogin.framework/NaverThirdPartyLogin  for architecture arm64

이전에 같은 이슈로 등록 된적이 있으나, 제 버전 보다 낮은 버전이었습니다.
이전 이슈사항에 있는 대로 EXCLUDED ARCHS 에 설정해 보았으나 오류가 발생하고 있습니다. 

### Tested environment (Emulator? Real Device?)
시뮬레이터 버전 iPhone 8 plus 14.1, 13.6, 13.7

**Comment by mym0404** [comment]
현재 `2.3.1` 버전으로 문제가 있으면 댓글 남겨주세요!
