### ISSUE TITLE
네이버 앱이 없을시 네이버 로그인시 errCode: user_cancel, errDesc: user_cancel 문제

### ISSUE THREAD

**Issue by leechanghoon3024** [react-native-seoul/react-native-naver-login#69]
### Version of naver-login libraries

 "@react-native-seoul/naver-login": "^2.1.0",

### Version of react-native

0.63

### Platforms you faced the error (IOS or Android or both?)

Android 

### Tested environment (Emulator? Real Device?)

 ^2.1.0 기준

테스트 기기에 네이버 앱이 없을때 네이버 로그인시 웹뷰가 출력되면서 동의를 눌렀을 경우,
"errCode: user_cancel, errDesc: user_cancel" 로그가 출력되던 문제가 있었는데

해당 @react-native-seoul/naver-login/android/build.grandle 의

```
DEFAULT_BUILD_TOOLS_VERSION = 29.0.2
```
dependencies block의 

```
implementation 'com.naver.nid:naveridlogin-android-sdk:4.2.5 > implementation 'com.naver.nid:naveridlogin-android-sdk:4.2.6
```
으로 올려주니 해결되었습니다. 

네아로 sdk 4.2.6은 해당 이슈를 해결한 sdk로 똑같은 이슈가 생기지않을려면 업데이트가 필요할거같습니다.

**Comment by Louis-jk** [comment]
감사합니다! gradle 오류에 머리가 아팠었는데 정말 감사합니다! 정말 중요한 정보네요!

**Comment by mym0404** [comment]
해결법입니다. [Solution 출처](https://medium.com/mindorks/avoiding-conflicts-in-android-gradle-dependencies-28e4200ca235)

`app/build.gradle` 에 아무데나 (전 top level에 함) 다음과 같은 코드를 넣어줘서 gradle dependencies 를 고정시켜주세요

```groovy
configurations.all {
    resolutionStrategy {
        force 'com.naver.nid:naveridlogin-android-sdk:4.2.6'
    }
}
```
