### ISSUE TITLE
로그인창이 느리게 출력되는 문제

### ISSUE THREAD

**Issue by morishjs** [react-native-seoul/react-native-naver-login#74]
### Version of naver-login libraries

2.1.0

https://user-images.githubusercontent.com/6479241/117102942-4c415280-adb4-11eb-98e0-ac1061b4865a.MP4

### Version of react-native

0.64

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

빠르게 팝업이 출력되어야 합니다.

### Actual behavior

팝업이 대략 10초 뒤에 출력됩니다. 이후에 다시 시도하면 정상적으로 팝업이 빠르게 출력됩니다. 앱 설치 후 최초 로그인시 발생하는 문제입니다.

### Tested environment (Emulator? Real Device?)

- 에뮬레이터에서는 문제 없습니다.

- 제 iPhone SE2 에서 늦게 출력됩니다. (동영상 참조)

**Comment by mym0404** [comment]
최신 버전 `2.3.1` 에서 재현되는지 확인하고 댓글 남겨주세요!
