### ISSUE TITLE
Android 설정 안내문 오타(?) 수정 건의

### ISSUE THREAD

**Issue by redvelvet-fan** [react-native-seoul/react-native-naver-login#81]
### Actual behavior

https://github.com/react-native-seoul/react-native-naver-login#android
여기에 1.Open ...
MainActivity.java 가 아니라
MainApplication.java 로 수정해야할것 같습니다!

**Comment by blackstar0223** [comment]
고쳐서 PR 해보려 했는데 엑세스 불가네요 ㅠㅠ 중요한 내용이라 수정 꼭 필요할 것 같습니다

**Comment by hyochan** [comment]
> 고쳐서 PR 해보려 했는데 엑세스 불가네요 ㅠㅠ 중요한 내용이라 수정 꼭 필요할 것 같습니다

포크 떠서 PR 올려주시면 되세요!

**Comment by blackstar0223** [comment]
#90 관련 PR 올렸습니다!
