### ISSUE TITLE
모듈 install 이후 cannot resolve symbol 문제

### ISSUE THREAD

**Issue by magoyoo** [react-native-seoul/react-native-naver-login#82]
### Version of naver-login libraries

 "@react-native-seoul/naver-login": "^2.1.0"

### Version of react-native

 "react-native": "0.64.1",

### Platforms you faced the error (IOS or Android or both?)

ANDROID

### Expected behavior

android studio link

### Actual behavior

 "@react-native-seoul/naver-login" 를 install 한 후 안드로이드 스튜디오에서 아래와 같이 대부분의 모듈이 sync가 깨지는 문제가 발생합니다.  모듈을 지우고 캐시를 지운 후 다시 리프래쉬하면 아래의 애러 메시지는 없어집니다. 애러를 무시하고 빌드하면 빌드는 정상적으로 되고 기능도 정상적으로 구동됩니다. 

![image](https://user-images.githubusercontent.com/83945417/120883661-67082080-c619-11eb-8556-c58f8c5c3b5e.png)

### Tested environment (Emulator? Real Device?)

MAC OS(bir sur) Android studio (4.2.1)

**Comment by mym0404** [comment]
로컬 환경 IDE 캐시 문제로 보입니다.
현재 최신 버전인 `2.3.1` 버전으로 시도해보시고 문제가 있으시면 다시 댓글 남겨주세요.
