### ISSUE TITLE
ios 네이버 앱만 켜졌다가 return 이 없음

### ISSUE THREAD

**Issue by yhl0519** [react-native-seoul/react-native-naver-login#87]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "^2.1.0",

### Version of react-native

"react-native": "0.63.4",

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

로그인 버튼 클릭시 네이버 앱 켜지고 로그인 후 사용자 정보 return

### Actual behavior

안드로이드에서는 NaverLogin.login, getProfile 둘다 잘 되는데
아이폰에서는 네이버 앱만 왔다갔다하고 아무 return이 없습니다.
에러도 안나오고 토큰도 안나옵니다ㅜㅜ

코드
```
const naverLogin = () => {
  return new Promise((resolve, reject) => {
    const initials = Platform.OS === "ios" ? iosKeys : androidKeys;
    console.log('naverLogin start! OS: ',Platform.OS)
    NaverLogin.login(initials, (err, token) => {
      if (err) {
        console.log('err > ',err)
        reject(err);
      } else {
        console.log('token > ',token)
        resolve(token);
      }
    });
  });
};
```

console
```
[Tue Jun 29 2021 11:44:21.400]  LOG      signInWithNaver start
[Tue Jun 29 2021 11:44:21.700]  LOG      naverLogin start! OS:  ios
```

### Tested environment (Emulator? Real Device?)

아이폰8 (실제기기)

**Comment by Dev-YoonSe** [comment]
저도 동일한 증상이 있습니다. 앱이 아닌 로그인 페이지로는 정상적인 return 값이 있지만 네이버 앱이 설치된 경우에는 return 이 없었습니다ㅠㅠ...

**Comment by circlinDev** [comment]
동일이슈입니다. 로그인시 로그인은 되는거같은데 앱으로 다시 돌아오고 아무반응도 없네욤

**Comment by blackstar0223** [comment]
Iphone 12 mini에서 동일 이슈 발생합니다. 브라우저를 통한 네이버 로그인은 정상 작동합니다.

**Comment by blackstar0223** [comment]
우선 #57 이슈 [코멘트](https://github.com/react-native-seoul/react-native-naver-login/issues/57#issuecomment-611807633)에 언급된 것처럼 모듈 코드를 직접 수정하여 IOS에서 네이버 로그인 시도 시 앱이 강제적으로 실행되지 않도록 조치하는 방법이 있습니다. 이슈 해결 때까지는 이렇게 해두어야겠네요.

**Comment by yhl0519** [comment]
이제 잘 되네요 ㅎㅎ
감사합니다!!
