### ISSUE TITLE
네이버로그인 후 회원 프로필 조회

### ISSUE THREAD

**Issue by yhl0519** [react-native-seoul/react-native-naver-login#97]
### Version of naver-login libraries

"@react-native-seoul/naver-login": "^2.1.0"

### Version of react-native

"react-native": "0.63.4"

### Platforms you faced the error (IOS or Android or both?)

IOS, Android

### Expected behavior

네이버로그인 후 사용자 프로필정보 조회

### Actual behavior

getProfile 잘 되나요..?

```
import { NaverLogin, getProfile } from "@react-native-seoul/naver-login";

const naverLogin = () => {
  return new Promise((resolve, reject) => {
    const initials = Platform.OS === "ios" ? iosKeys : androidKeys;
    NaverLogin.login(initials, (err, token) => {
      if (err) {
        reject(err);
      } else {
        resolve(token);
      }
    });
  });
};


const signInWithNaver = async () => {
  try {
    const naverToken = await naverLogin();
    const profile = await getProfile(naverToken.accessToken);
    console.log('profile > ',profile) // 여기서 리턴값에서 email 정보가 오는거 아닌가요?ㅜㅜ
  } catch (err) {
  }
};
```

저는 리턴이 이런식으로오는데 이렇게오는게 맞나요.?

{"message": "success", "response": {"id": "id 정보"}, "resultcode": "00"}

네이버에서 https://developers.naver.com/docs/login/profile/profile.md 여기 5번 출력결과 보면 다른정보도 주는거같습니다..
사실 라이브러리말고 네이버문서 따라해봐도 결과가 똑같이나옵니다..
라이브러리문제가 아니라는건 알고있지만 네이버포럼에 물어봐도 답이없네요ㅜㅜ
혹시 알고계시다면 답변 부탁드립니다!!

**Comment by mym0404** [comment]
개발자 콘솔에 
![image](https://user-images.githubusercontent.com/33388801/196618138-68f23b58-c96d-4aa6-b48d-bd555a85511d.png)
여기서 항목을 추가하고 로그인 연동시에 사용자가 이메일 항목을 선택할 수 있도록 잘 뜨나요?

**Comment by mym0404** [comment]
현재 라이브러리 코드는 네이티브 SDK를 이용하는게 아닌 첨부주신 문서에서 나와있는 url에 fetch를 때리고 응답을 그대로 JSON 으로 반환해주는 역할밖에 하지 않습니다. 따라서 라이브러리 이슈가 아닐것같습니다.
