### ISSUE TITLE
네이버 sdk의 경로를 못찾음

### ISSUE THREAD

**Issue by 172900** [react-native-seoul/react-native-naver-login#99]
### Version of naver-login libraries

@react-native-seoul/naver-login": "^2.1.1

0.65.1

### Platforms you faced the error (IOS or Android or both?)

android

### Expected behavior

npm run andorid 시에 빌드

### Actual behavior

![image](https://user-images.githubusercontent.com/37587416/137238380-17cb59d8-d6bf-452a-8d77-b8d7c83ea2fb.png)

### Tested environment (Emulator? Real Device?)
enulator

네이버 sdk의 경로를 못찾는 것 같은데 혹시 해결 방안이 있을까요?
kakao로그인에서는 
build.gradle(Project)에 

> maven { url 'https://devrepo.kakao.com/nexus/content/groups/public/' }

을 추가해서 해결했는데 비슷한 방법으로 해결할 수 있는 방법이 있을까요?

@hyochan

**Comment by gibuhapi2** [comment]
react 0.65 version에서 jcenter()를 없애라고 해서 없앴는데, 그다음부터 경로를 못 찾더라고요

여러시도하다가, 다시 살렸더니,잘 찾네요 리액트네이티브 이놈들

**Comment by jwjeong79** [comment]
저도 똑같이 네이버 sdk 경로를 찾지 못하는 오류가 발생합니다. jcenter에서 이관하면 진행할지 로컬에 추가하고 진행할지 고민 중입니다.

**Comment by park12sj** [comment]
jcenter가 내년쯤에 shut down 될 예정인거 같은데요
jcenter 없이 해결하신 분은 없으신건가요?

**Comment by park12sj** [comment]
jcenter가 내년 초 shut down  예정이던데 없이 해결하신 분은 안 계신가요?

**Comment by park12sj** [comment]
> 저도 똑같이 네이버 sdk 경로를 찾지 못하는 오류가 발생합니다. jcenter에서 이관하면 진행할지 로컬에 추가하고 진행할지 고민 중입니다.

혹시 로컬에 추가를 어떻게 하는지 여쭤봐도 될까요?

**Comment by mym0404** [comment]
duplicate of #104
